language: python
sudo: false

env:
  - py27-plone_org4
    TOXENV=py27-plone_org_4
  - py27-plone_org5
    TOXENV=py27-plone_org_5
  - py27-plone_classic
    TOXENV=py27-plone_classic
  - py34-plone_org_4
    TOXENV=py3.4-plone_org_4
  - py34-plone_org_5
    TOXENV=py3.4-plone_org_5
  - py34-plone_classic
    TOXENV=py3.4-plone_classic
  - py35-plone_org_4
    TOXENV=py35-plone_org_4
  - py35-plone_org_5
    TOXENV=py35-plone_org_5
  - py35-plone_classic
    TOXENV=py35-plone_classic
  - py36-plone_org_4
    TOXENV=py36-plone_org_4
  - py36-plone_org_5
    TOXENV=py36-plone_org_5
  - py36-plone_classic
    TOXENV=py36-plone_classic
  - pypy-plone_org_4
    TOXENV=pypy-plone_org_4
  - pypy-plone_org_5
    TOXENV=pypy-plone_org_5
  - pypy-plone_classic
    TOXENV=pypy-plone_classic
  - isort
    TOXENV=isort
  - flake8
    TOXENV=flake8

matrix:
    exclude:
        - python: "2.7"
          env:
            - py34-plone_org_4
            - py34-plone_org_5
            - py34-plone_classic
            - py35-plone_org_4
            - py35-plone_org_5
            - py35-plone_classic
            - py36-plone_org_4
            - py36-plone_org_5
            - py36-plone_classic
            - pypy-plone_org_4
            - pypy-plone_org_5
            - pypy-plone_classic
            - isort
            - flake8
        - python: "3.4"
          env:
            - py27-plone_org_4
            - py27-plone_org_5
            - py27-plone_classic
            - py35-plone_org_4
            - py35-plone_org_5
            - py35-plone_classic
            - py36-plone_org_4
            - py36-plone_org_5
            - py36-plone_classic
            - pypy-plone_org_4
            - pypy-plone_org_5
            - pypy-plone_classic
            - isort
            - flake8
        - python: "3.5"
          env:
            - py27-plone_org_4
            - py27-plone_org_5
            - py27-plone_classic
            - py34-plone_org_4
            - py34-plone_org_5
            - py34-plone_classic
            - py36-plone_org_4
            - py36-plone_org_5
            - py36-plone_classic
            - pypy-plone_org_4
            - pypy-plone_org_5
            - pypy-plone_classic
            - isort
            - flake8
        - python: "3.6"
          env:
            - py27-plone_org_4
            - py27-plone_org_5
            - py27-plone_classic
            - py34-plone_org_4
            - py34-plone_org_5
            - py34-plone_classic
            - py35-plone_org_4
            - py35-plone_org_5
            - py35-plone_classic
            - pypy-plone_org_4
            - pypy-plone_org_5
            - pypy-plone_classic
        - python: "pypy"
          env:
            - py27-plone_org_4
            - py27-plone_org_5
            - py27-plone_classic
            - py34-plone_org_4
            - py34-plone_org_5
            - py34-plone_classic
            - py35-plone_org_4
            - py35-plone_org_5
            - py35-plone_classic
            - py36-plone_org_4
            - py36-plone_org_5
            - py36-plone_classic
            - isort
            - flake8
    include:
        # pyXX-plone_sunburst,pyXX-plone_barceloneta
        - python: "2.7"
          env:
            - py27-plone_org_4
            - py27-plone_org_5
            - py27-plone_classic
        - python: "3.4"
          env:
            - py34-plone_org_4
            - py34-plone_org_5
            - py34-plone_classic
        - python: "3.5"
          env:
            - py35-plone_org_4
            - py35-plone_org_5
            - py35-plone_classic
        - python: "3.6"
          env:
            - py36-plone_org_4
            - py36-plone_org_5
            - py36-plone_classic
            - isort
            - flake8
        - python: "pypy"
          env:
            - pypy-plone_org_4
            - pypy-plone_org_5
            - pypy-plone_classic

install:
    - travis_retry pip install tox coveralls coverage

script:
    - travis_retry tox

cache:
    directory:
        - $HOME/.cache/pip

notifications:
    email: false
